import numpy as np
a=np.matrix("1,2,3;4,5,6;7,6,0")
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
b=np.matrix("1.5,2.5;3.9,4.9;1.2,3.2")
print(b)
print(b.ndim)
print(b.H)
print(b.A)
print(b.dtype)
print(b.shape)
print(b.T)
print(b)